### ISSUE TITLE
Can't start server due to error: "Cannot find module './bundle/manifest.json'"

### ISSUE THREAD

**Issue by lukaswuerzburger** [emanuelschmitt/maumau#15]
Console Output:

```
yarn run v1.22.4
$ nodemon src/server/main.ts
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts,tsx
[nodemon] starting `ts-node -P tsconfig.json src/server/main.ts`
Error: Cannot find module './bundle/manifest.json'
Require stack:
- /Users/lukaswuerzburger/Documents/projects/emanuelschmitt/maumau/packages/maumau-client/index.ts
- /Users/lukaswuerzburger/Documents/projects/emanuelschmitt/maumau/packages/maumau-server/src/server/ssr-router.ts
- /Users/lukaswuerzburger/Documents/projects/emanuelschmitt/maumau/packages/maumau-server/src/server/express-server.ts
- /Users/lukaswuerzburger/Documents/projects/emanuelschmitt/maumau/packages/maumau-server/src/server/main.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/lukaswuerzburger/Documents/projects/emanuelschmitt/maumau/packages/maumau-client/index.ts:3:42)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module.m._compile (/Users/lukaswuerzburger/Documents/projects/emanuelschmitt/maumau/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/lukaswuerzburger/Documents/projects/emanuelschmitt/maumau/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by emanuelschmitt** [comment]
Wenn das kommt, einmal den client builden. 
```
cd packages/maumau-client && yarn build
```
Müsste ich mal noch in eine Readme packen.
