### ISSUE TITLE
Reenable bot delay and investigate in concurrency issue

### ISSUE THREAD

**Issue by lukaswuerzburger** [emanuelschmitt/maumau#40]
```
[2020-10-23 09:06:00] DEBUG: Reducer: Emiting action PLAY_REGULAR_CARD
[2020-10-23 09:06:04] DEBUG: Reducer: Emiting action PLAY_JACK
[2020-10-23 09:06:06] DEBUG: Reducer: Emiting action PLAY_EIGHT
[2020-10-23 09:06:09] DEBUG: Reducer: Emiting action KANNET_AND_DRAW
[2020-10-23 09:06:09] DEBUG: Reducer: Emiting action KANNET
[2020-10-23 09:06:11] DEBUG: Reducer: Emiting action KANNET_AND_DRAW

..../emanuelschmitt/maumau/packages/maumau-server/src/game/game-state.ts:96
      throw new Error('forbidden action: ' + action.type);
            ^
Error: forbidden action: KANNET_AND_DRAW
    at GameState.dispatchForPlayer (..../emanuelschmitt/maumau/packages/maumau-server/src/game/game-state.ts:96:13)
    at BotController.onBotPlaying (..../emanuelschmitt/maumau/packages/maumau-server/src/game/game-state.ts:43:14)
    at Timeout._onTimeout (..../emanuelschmitt/maumau/packages/maumau-server/src/controllers/bot.ts:48:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by lukaswuerzburger** [comment]
Hattest du das nicht gefixt @emanuelschmitt ?
